name: e_pos
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  sqflite: ^2.3.3+1
  flutter_svg: ^2.0.5
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
